### ISSUE TITLE
Update available

### ISSUE THREAD

**Issue by Witar23** [hillaliy/homebridge-haa-downloader#2]
I have found out one more issue,
Downloading works perfect, but whenever I restart HomeBridge it shows me that Update for HAA are available although they have been downloaded and installed:

{
  name: 'Home Accessory Architect v10.2.0 Kestrel',
  tag: { name: '10.2.0' },
  isPrerelease: false,
  publishedAt: '2022-02-01T19:53:57Z',
  url: 'https://github.com/RavenSystem/haa/releases/tag/10.2.0'
}
[2/2/2022, 1:10:32 PM] [HAA-Downloader] An update is available! Home Accessory Architect v10.2.0 Kestrel
[2/2/2022, 1:10:32 PM] [HAA-Downloader] Latest Release: 10.2.0

**Comment by hillaliy** [comment]
I know. I'm still thinking how to fix it

**Comment by hillaliy** [comment]
Fix with version 1.1.0. but you will need to create "currentVersion.txt" (with a value like this 1.0.0) file to your homebridge directory before update.
I need to fix it.

**Comment by hillaliy** [comment]
version 1.1.1 - currentVersion.txt file will create automatically when install the plugin
